version: '3'

services:
  mysql:
    image: ${DOCKER_MYSQL_IMAGE}
    container_name: ${MYSQL_DATABASE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${DOCKER_MYSQL_PORT}"
    networks:
      - ${DOCKER_NETWORK}

networks:
  app-network:
